import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary': '#ffffff',
        'surface-container': '#e6f0eb',
        'surface-bright': '#f2fcf6',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#afcdbe',
        'primary-container': '#132e24',
        'on-primary': '#ffffff',
        'on-tertiary-fixed-variant': '#244e3e',
        'error': '#ba1a1a',
        'on-tertiary-container': '#6e9a86',
        'primary-fixed': '#cbeada',
        'on-error-container': '#93000a',
        'inverse-surface': '#29322f',
        'on-surface-variant': '#424845',
        'tertiary-fixed': '#beedd7',
        'secondary-fixed-dim': '#eec14b',
        'on-background': '#141d1a',
        'on-primary-fixed': '#042017',
        'inverse-primary': '#afcdbe',
        'on-secondary-fixed-variant': '#5a4300',
        'on-error': '#ffffff',
        'outline-variant': '#c2c8c3',
        'surface-dim': '#d2dcd7',
        'primary': '#001910',
        'on-secondary-fixed': '#251a00',
        'background': '#f2fcf6',
        'on-primary-container': '#7a9789',
        'tertiary-fixed-dim': '#a3d0bb',
        'on-surface': '#141d1a',
        'error-container': '#ffdad6',
        'surface-variant': '#dbe5e0',
        'on-primary-fixed-variant': '#314c41',
        'inverse-on-surface': '#e9f3ee',
        'secondary-fixed': '#ffdf98',
        'surface-container-high': '#e0eae5',
        'secondary': '#775a00',
        'outline': '#727974',
        'surface': '#f2fcf6',
        'on-secondary-container': '#735700',
        'tertiary-container': '#003022',
        'surface-container-highest': '#dbe5e0',
        'surface-tint': '#496458',
        'on-tertiary': '#ffffff',
        'tertiary': '#001910',
        'secondary-container': '#fece57',
        'surface-container-low': '#ecf6f1',
        'on-tertiary-fixed': '#002116',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        sharp: '0px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        gutter: '1.5rem',
        margin: '2rem',
      },
      fontFamily: {
        serif: ['var(--font-eb-garamond)', 'EB Garamond', 'serif'],
        sans: ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        mono: ['var(--font-jetbrains-mono)', 'JetBrains Mono', 'monospace'],
        'body-lg': ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        'headline-md': ['var(--font-eb-garamond)', 'EB Garamond', 'serif'],
        'headline-lg': ['var(--font-eb-garamond)', 'EB Garamond', 'serif'],
        'label-sm': ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        'headline-lg-mobile': ['var(--font-eb-garamond)', 'EB Garamond', 'serif'],
        'body-sm': ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        'headline-sm': ['var(--font-eb-garamond)', 'EB Garamond', 'serif'],
        'label-lg': ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        'display-lg': ['var(--font-eb-garamond)', 'EB Garamond', 'serif'],
        'body-md': ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        'metric-display': ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        'display-lg-mobile': ['var(--font-eb-garamond)', 'EB Garamond', 'serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'headline-md': ['26px', { lineHeight: '34px', fontWeight: '500' }],
        'headline-lg': ['38px', { lineHeight: '46px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '500' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-lg': ['13px', { lineHeight: '18px', letterSpacing: '0.06em', fontWeight: '600' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'metric-display': ['44px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};

export default config;
